// next/components/development/LoginTest.tsx
'use client';
import { sendRest } from '@/services/api/rest';
import { useRouter } from 'next/navigation';

export default function LoginTest() {
  const router = useRouter();

  const execLogin = async () => {
    const data = {};
    const uri = '/login';

    const res = await sendRest<{ message: string }>(uri, data);

    console.log('res', res);

    router.push('/');
  };

  const execLogout = async () => {
    const data = {};
    const uri = '/logout';

    const res = await sendRest<{ message: string }>(uri, data);

    console.log('res', res);

    //router.push('/');
    location.href = "/";
  };

  return (
    <div>
      <button type="button" onClick={execLogin} className="app-btn-primary">
        ログイン
      </button>
      <button type="button" onClick={execLogout} className="app-btn-primary ml-5">
        ログアウト
      </button>
    </div>
  );
}

// nuxt/app/components/development/LoginTest.vue
<script setup lang="ts">
import { sendRest } from '@/services/api/rest';
import { useRouter } from 'vue-router';

const router = useRouter();

const execLogin = async () => {
  const data = {};
  const uri = '/auth/login';

  try {
    const res = await sendRest<{ message: string }>(uri, data);
    console.log('res', res);

    // Nuxtルーターで遷移
    router.push('/');
  } catch (e) {
    console.error(e);
  }
};

const execLogout = async () => {
  const data = {};
  const uri = '/auth/logout';

  try {
    const res = await sendRest<{ message: string }>(uri, data);
    console.log('res', res);

    // SSR/CSR問わず確実にリロードしたい場合
    location.href = '/';
  } catch (e) {
    console.error(e);
  }
};
</script>

<template>
  <div>
    <button @click="execLogin" class="app-btn-primary">ログイン</button>
    <button @click="execLogout" class="app-btn-primary ml-5">ログアウト</button>
  </div>
</template>
