// nuxt/app/pages/posts.vue
<script setup lang="ts">
const posts = await queryCollection('post').order('date', 'DESC').all();

console.log(posts);
</script>

<template>
  <div>
    <h2>Posts</h2>

    <div class="space-y-5 p-10">
      <div v-for="post in posts" :key="post.path">
        <NuxtLink :to="post.path">
          <div class="border p-5">
            <div>{{ post.title }}</div>

            <div>{{ post.description }}</div>
          </div>
        </NuxtLink>
      </div>
    </div>
  </div>
</template>

// next/app/posts/page.tsx
import Link from 'next/link';

import ServerLayout from '@/components/layouts/ServerLayout';

import { posts } from '@/.velite';

export default function Posts() {
  console.log('Posts');

  return (
    <ServerLayout>
      <div>
        <h2 className="app-h2">Blog</h2>

        <div>
          {posts.map((post) => (
            <Link href={`/article/${post.slug}`} prefetch={false} key={post.slug}>
              <article className='border-2 p-5'>
                <h3 className='app-h3'>{post.title}</h3>
                <div>
                  {post.description}
                </div>
              </article>
            </Link>
          ))}
        </div>
      </div>
    </ServerLayout>
  );
}
