// next/components/development/LoginTest.tsx
'use client';
import { sendRest } from '@/services/api/rest';
import { useRouter } from 'next/navigation';

export default function LoginTest() {
  const router = useRouter();

  const execLogin = async () => {
    const data = {};
    const uri = '/login';

    const res = await sendRest<{ message: string }>(uri, data);

    console.log('res', res);

    router.push('/');
  };

  const execLogout = async () => {
    const data = {};
    const uri = '/logout';

    const res = await sendRest<{ message: string }>(uri, data);

    console.log('res', res);

    router.push('/');
  };

  return (
    <div>
      <button type="button" onClick={execLogin} className="app-btn-primary">
        ログイン
      </button>
      <button type="button" onClick={execLogout} className="app-btn-primary ml-5">
        ログアウト
      </button>
    </div>
  );
}

// astro/src/components/development/LoginTest.vue
<script setup lang="ts">
import { navigate } from 'astro:transitions/client';

import { Auth } from '@/services/auth/auth';

const execLogin = async () => {
  await Auth.login();
  navigate('/');
};

const execLogout = async () => {
  await Auth.logout();
  navigate('/');
};

const execMe = async () => {
  Auth.me();
};
</script>

<template>
  <div>
    <button @click="execLogin" class="app-btn-primary">ログイン</button>
    <button @click="execLogout" class="app-btn-primary ml-5">ログアウト</button>
    <button @click="execMe" class="app-btn-primary ml-5">
      ログインチェック
    </button>
  </div>
</template>
